#!/usr/bin/env bash
#tranfer a file from the local machine to a remote machine

if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	if [ $# -eq 4 ]
	then
		scp -o strictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":"~/"
	elif [ $# -eq 3 ]
	then
		scp -o strictHostKeyChecking=no "$1" "$3"@"$2":"~/"
	fi
fi

