#!/usr/bin/env bash
#install and configure nginx on

apt-get -y update && apt-get install -y nginx
if [ $? -eq 0 ] 
then
	#create directory and file to be served
	mkdir -p /var/www/school/html
	chown -R $USER:$USER /var/www/school/html
	chown -R 755 /var/www
	echo "Hello World!!" > /var/www/school/html/index.html

	#configure nginx
	cp /etc/nginx/sites-available/default /etc/nginx/sites-available/school
	echo -e "server {
	listen 80;
	listen [::]:80;
	root /var/www/school/html;
	index index.html;
	location / {
		try_files $url $url/ =404;
	}
	
}" > /etc/nginx/sites-available/school
ln -s /etc/nginx/sites-available/school /etc/nginx/sites-enabled/

systemctl restart nginx
if [ $? -ne 0 ]
then 
	echo "Could not start nginx"
fi
else
	echo "Could not install nginx."
fi
