#!/usr/bin/env bash
#configure nginx to redirect /redirect_me to a different page
echo -e \
"http {
    root /var/www/school;
    index index.html;
    server {
        listen 80;
        location \ {
        }
    rewrite ^/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;
    }
}
events {
}" > /etc/nginx/nginx.conf

systemctl restart nginx
