#!/usr/bin/env bash
#install and configure nginx

apt-get update -y &&\
apt-get install nginx

if [ $? -eq 0 ]
then
	echo -e \
"
http {
	root /var/www/school;
	index index.html index.htm;
	server {
		listen 80;
		location \ {
		}
	}
	events {
	}
}
" > /etc/nginx/nginx.conf

mkdir -p /var/www/school
echo "Hello World" > /var/www/school/index.html
chmod 755 /var/www/school
chmod 755 /var/www/school/index.html

systemctl start nginx

if [ $? -eq 0 ]
then 
	echo "nginx is running..."
else
	echo "Failed to run nginx"
	exit 1
fi

else
	echo "Could not install nginx"
	exit 1
fi
exit 0
