#!/usr/bin/env bash
#prints "Best school" 10 times and Hi in the 9th iteration

count=1
while [ $count -le 10 ]
do
    echo "Best School"
    if [ $count -eq 9 ]
    then
	    echo "Hi"
    fi
    ((count++))
done
