#!/usr/bin/env bash
#loop from 1 through 20 and print "bad luck fron China" on the 4th iteration, "bad luck  from Japan" 9th iteration and "Bad luck from Italy" on the 7th iteration

count=1
while [ $count -le 20  ]
do 
	echo "$count"
	case $count in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((count++))
done
