#!/usr/bin/env bash
#This script configures ufw to block incoming traffic
#except for ssh, http and https

ufw default deny incoming
ufw default allow outgoing
ufw allow 22
ufw allow 80
ufw allow 443
ufw enable
